version: '3'

services:

  snipe-mysql:
    container_name: snipe-mysql
    restart: always
    image: mysql:5.6
    volumes:
      - snipesql-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "<<YOUR MYSQL ROOT PASSWORD>>"
      MYSQL_DATABASE: "snipeit"
      MYSQL_USER: "snipeit"
      MYSQL_PASSWORD: "<<YOUR MYSQL USER PASSWORD>>"
    ports:
      - 3306:3306

  snipeit:
    container_name: snipeit
    restart: always
    image: snipe/snipe-it:latest
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_KEY: "<<YOUR GENERATED KEY HERE>>"
      APP_URL: "https://<<IP ADDRESS>>:<<PORT>>"
      APP_TIMEZONE: "US/Eastern"
      APP_LOCALE: "en"
      MYSQL_ROOT_PASSWORD: "<<YOUR MYSQL ROOT PASSWORD>>"
      MYSQL_DATABASE: "snipeit"
      MYSQL_USER: "snipeit"
      MYSQL_PASSWORD: "<<YOUR MYSQL USER PASSWORD>>"
      MYSQL_PORT_3306_TCP_ADDR: "mysql"
      MAIL_PORT_587_TCP_ADDR: "<<FQDN OF YOUR MAIL SERVER>>"
      MAIL_PORT_587_TCP_PORT: "587"
      MAIL_ENV_FROM_ADDR: "<<SEND FROM ADDRESS>>"
      MAIL_ENV_FROM_NAME: "<<SEND FROM NAME>>"
      MAIL_ENV_ENCRYPTION: "tls"
      MAIL_ENV_USERNAME: "<<MAIL SERVER LOGIN>>"
      MAIL_ENV_PASSWORD: "<<MAIL SERVER PASSWORD>>"
    links:
      - snipe-mysql:mysql
    ports:
      - 80:80
      - 443:443

volumes:
  snipesql-vol:
